version: "3.7"

networks:
  proxy:
    external: true

services:
  app:
    build: .
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.adnumaz.loadbalancer.server.port=80 # optional
      - traefik.http.routers.adnumaz.rule=Host(`adnumaz.homes`)
      - traefik.http.routers.adnumaz.entrypoints=web
      - traefik.http.routers.adnumaz-https.rule=Host(`adnumaz.krassimir.dev`)
      - traefik.http.routers.adnumaz-https.entrypoints=websecure

  db:
    networks:
      - gateway
    ports:
      - 1434:1433
    restart: unless-stopped

  tracker:
    networks:
      - proxy
    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.services.adnumaz-tracker.loadbalancer.server.port=6969 # optional
      - traefik.http.routers.adnumaz-tracker.rule=Host(`adnumaz-tracker.homes`)
      - traefik.http.routers.adnumaz-tracker.entrypoints=web
      - traefik.http.routers.adnumaz-tracker-https.rule=Host(`adnumaz-tracker.krassimir.dev`)
      - traefik.http.routers.adnumaz-tracker-https.entrypoints=websecure
