version: "3.7"

networks:
  internal:
    internal: true
  gateway:

services:
  app:
    depends_on:
      - db
    networks:
      - internal
      - gateway
    environment:
      - TRACKER_API=http://tracker:$TRACKER_API_PORT
      - FILE_UPLOAD_DIRECTORY=/torrents
      - ASPNETCORE_ENVIRONMENT=Production
      - SQL_CONNECTION_STRING=Server=db;Database=master;User=sa;Password=$SA_PASSWORD;MultipleActiveResultSets=True    

    volumes:
      # This volume must be owned by root
      - ./appdata/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      - ./appdata/Torrents:/torrents
  
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - internal
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=$SA_PASSWORD
    volumes:
      # These volumes must be owned by UID 10001
      - ./appdata/data:/var/opt/mssql/data
      - ./appdata/log:/var/opt/mssql/log
      - ./appdata/secrets:/var/opt/mssql/secrets

  tracker:
    build: ../../vendor/bittorrent-tracker-rest
    networks:
      - internal
      - gateway
    environment:
      - API_PORT:$TRACKER_API_PORT
    ports:
      - 6969:6969/tcp
      - 6969:6969/udp
      - 8085:8080
